#!/bin/bash
# Synopsis: Select editor to edit files
# Usage: select-editor [FILES]

editors=(
	"vi"
	"nvi"
	"vim"
	"nvim"
)

[ $# -eq 0 ] && exit 1
answer=$(bashmenu "${editors[@]}")
[ -z "$answer" ] && exit
exec "$answer" "$@"
